### ISSUE TITLE
Change default RTD config to use pip and extras-require

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#387]
We should update the package template to match the core package in terms of RTD configuration - basically having a configuration that uses pip and relies on the extras-requires (which can default to sphinx-astropy)

```
build:
    image: latest

python:
  version: 3.6
  pip_install: true
  extra_requirements: ['docs']
```
