### ISSUE TITLE
Automate default labels?

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#501]
Now that Cron CI tests are established, I was thinking that there are also a useful set of tests that can be run on the repository itself. Besides labels, such checks could be for dependencies (though Dependabot can do that), checks on submodules, updating the contributors list, checking the copyright dates on the license, etc.

This issue is to suggest a means to automate labels.

Something like https://github.com/crazy-max/ghaction-github-labeler can be used to set up labels on start and keep labels up-to-date. I was thinking of labels like: no-changelog-needed, API change, Bug, Docs, 🔥, needs-discussion, etc.
The advantage of this automated approach, particularly the suggested action, is that we can have a common set of tags, sharing colors and descriptions, between packages. Also, unifying the colors within a package is a bonus.

- - -
Possible Action
```
# GitHub Actions workflow that runs on a cron schedule.

name: Scheduled Repo Actions

on:
  schedule:
    # run at midnight on the first of the month.
    - cron: '0 0 1 * *'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
```

Example of some labels
```json
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
- name: "wontfix_it"
  color: "000000"
  description: "This will not be worked on"
  from_name: "wontfix"
```
